name: Build & Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            EXT=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/change_case_${{ matrix.goos }}${EXT} main.go
          echo ${{ github.ref_name }}

      - name: Package Windows binary
        if: matrix.goos == 'windows'
        run: |
          cd dist
          zip change_case_windows.zip change_case_windows.exe
          cd ..

      - name: Create .deb package (only on Linux)
        if: matrix.goos == 'linux'
        run: |
          mkdir -p myapp/DEBIAN
          cat <<EOF > myapp/DEBIAN/control
          Package: change-case
          Version: ${GITHUB_REF_NAME#v}
          Architecture: amd64
          Maintainer: You <labs@dksengine.com>
          Description: CLI to change case
          EOF

          mkdir -p myapp/usr/local/bin
          cp dist/change_case_linux myapp/usr/local/bin/change_case
          dpkg-deb --build myapp
          mv myapp.deb dist/change_case_linux.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.goos }}
          path: dist/*


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-linux
          path: dist/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-windows
          path: dist/windows

      - name: List files (debug)
        run: ls -R dist/

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

