name: Build & Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            EXT=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/change_case_${{ matrix.goos }}${EXT} main.go

      - name: Create .deb package (only on Linux)
        if: matrix.goos == 'linux'
        run: |
          mkdir -p myapp/DEBIAN
          echo "Package: change-case
Version: ${GITHUB_REF_NAME}
Architecture: amd64
Maintainer: You <labs@dksengine.com>
Description: CLI to change case" > myapp/DEBIAN/control

          mkdir -p myapp/usr/local/bin
          cp dist/change_case_linux myapp/usr/local/bin/change_case
          dpkg-deb --build myapp
          mv myapp.deb dist/change_case_linux.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.goos }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
